### PR TITLE
NEO4J DataWareHouse-connector Blog Details Updated in README File

### PR DESCRIPTION
**Pull request by drraghavendra**
Description

Introduction To get Started Blog Guidance Detailing Information provided in the readme File of so as to make things ease of use for all the users https://github.com/neo4j-contrib/neo4j-dwh-connector

### CODE REVIEW

**Comment by drraghavendra** [comment]
Respected sir @conker84 please look in to this PR

**Comment by laeg** [comment]
@drraghavendra, thank you for the suggested update. This looks good, LGTM!

**Comment by conker84** [comment]
@drraghavendra thank you so much! Did you sign the [CLA](http://dist.neo4j.org/neo4j-cla.pdf?_ga=2.206275227.982981175.1674035939-604486005.1671302939)?

**Comment by conker84** [comment]
Hi @drraghavendra we have integrated you changes in our repo thank you so much for contributing

**Comment by drraghavendra** [comment]
> @drraghavendra thank you so much! Did you sign the [CLA](http://dist.neo4j.org/neo4j-cla.pdf?_ga=2.206275227.982981175.1674035939-604486005.1671302939)?

Sir CLA signed

**Comment by drraghavendra** [comment]
@conker84 sir please merge the pull Request.

**Pull request closed without merging**
